# Generated by Django 4.1 on 2023-02-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='series_order',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='SeriesPost',
        ),
    ]
