# Generated by Django 4.1 on 2023-02-03 11:40

from django.db import migrations, models
import django.db.models.deletion
import velogapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("velogapp", "0002_post_series_order_delete_seriespost"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(upload_to=velogapp.models.image_upload_path),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="velogapp.post",
                    ),
                ),
            ],
            options={
                "db_table": "velogapp_postimage",
            },
        ),
    ]
